---
title: "Dacon_1st_compitition"
output: html_document
---
Library packages
```{r}
library(data.table)
library(dplyr)
library(ggplot2)
library(xgboost)
library(lightgbm)
library(Matrix)
library(caret)
library(ranger)
```
Read dataset & binding
```{r}
test <- fread("../input/test.csv")
train <- fread("../input/train.csv")


glimpse(train)
glimpse(test)
colSums(is.na(train))
colSums(is.na(test))

test$Survived <- NA
train$Train_or_Test <- "Train"
test$Train_or_Test <- "Test"

all <- rbind(train,test)
glimpse(all)
```

Preprocessing & Feature engineering
```{r}
all$group <- gsub('(.*, )|(\\..*)', '', all$Name) # Using WildCard (*)

all$Last_name <- substring(all$Name,0,regexpr(",",all$Name)-1)
all$Last_name <- factor(all$Last_name)

parents <- c("Mr","Mrs","Dona","Mme","the Countess")
all$Parent <- 'Not Parent'
all$Parent[all$Parch > 0 & all$Age > 18 & all$group %in% parents] <- "Parents"
all$Parent <- factor(all$Parent)

all$Ticket_summary <- sub("..$", "", all$Ticket)
all$Ticket_summary <- factor(all$Ticket_summary)

levels(factor(all$group))
levels(factor(all$Last_name))
levels(factor(all$Ticket_summary))

public_or_private_officer <- c("Rev","Don","Dr","Major","Col","Capt")
nobless <-c("Lady","the Countess","Dona","Jonkheer","Sir") 
# male : "Rev. "," Don. "," Dr. "," Major. "," Sir. "," Col. "," Capt. "," Jonkeer. " 
# female : " Mme. "," Lady. "," Mlle. "," the Countess. "," Dona.

all$group[all$group %in% public_or_private_officer] <- "Officer"
all$group[all$group %in% nobless] <- "Nobless"
all$group[all$group == "Mlle"] <- "Miss"
all$group[all$group == "Ms"] <- "Miss"
all$group[all$group == "Mme"] <- "Mrs"


all$group <- factor(all$group)
all$Survived <- factor(all$Survived) 

### Missing Value Processing ###
all[is.na(all$Fare),'Fare'] <-  median(all$Fare,na.rm = T)
all$Fare <- log1p(all$Fare)
mr_age <- all %>% filter(group == "Mr") %>% select(Age)
mrs_age <- all %>% filter(group == "Mrs") %>% select(Age)
miss_age <- all %>% filter(group == "Miss") %>% select(Age)
master_age <- all %>% filter(group == "Master") %>% select(Age)
officer_age <- all %>% filter(group == "Officer") %>% select(Age)
nobless_age <- all %>% filter(group == "Nobless") %>% select(Age)

sum(nrow(mr_age),nrow(mrs_age),nrow(miss_age),nrow(officer_age),nrow(nobless_age),nrow(master_age))

mean_of_mr_age <- mean(mr_age[,1],na.rm=TRUE)
mean_of_mrs_age <- mean(mrs_age[,1],na.rm=TRUE)
mean_of_miss_age <- mean(miss_age[,1],na.rm = TRUE)
mean_of_master_age <- mean(master_age[,1],na.rm = TRUE)
mean_of_officer_age <- mean(officer_age[,1],na.rm = TRUE)
mean_of_nobless_age <- mean(nobless_age[,1],na.rm = TRUE)

na_loc <- which(is.na(all$Age))

for (i in na_loc) {
  if(all[i,'group'] == "Mr"){
    all$Age[i] = mean_of_mr_age
  } else if(all[i,'group'] == "Mrs"){
    all$Age[i] = mean_of_mrs_age
  } else if(all[i,'group'] == "Miss"){
    all$Age[i] = mean_of_miss_age 
  } else if(all[i,'group'] == "Master"){
    all$Age[i] = mean_of_master_age
  } else if(all[i,'group'] == "Officer"){
    all$Age[i] = mean_of_officer_age
  } else if(all[i,'group'] == "Nobless"){
    all$Age[i] = mean_of_nobless_age
  }
}
colSums(is.na(all))
### Age Discretzation###
for (i in 1:nrow(all)) {
  if(all[i,'Age'] < 15) {
    all$cat_age[i]=1
  } else if (15<=all[i,'Age'] & all[i,'Age'] < 65) {
    all$cat_age[i]=2
  } else {
    all$cat_age[i]=3
  }
}

all$cat_age <- factor(all$cat_age,labels=c("childhood","adolescence","senescence"))
### number of Family ###
for (i in 1:nrow(all)) {
  if(all[i,'SibSp'] == 0 & all[i,'Parch'] == 0) {
    all$Num_Family[i] =1
  } else {
    all$Num_Family[i] = all$SibSp[i] + all$Parch[i] + 1  
  }
}
for (i in 1:nrow(all)){
  if(all[i,'Num_Family'] == 1){
    all$Solo_Family[i] = "Solo"
  } else if(all[i,'Num_Family'] > 1 & all[i,'Num_Family'] <= 4){
    all$Solo_Family[i] = "Small Family"
  } else {
    all$Solo_Family[i] = "Large Family"
  }
}
all$Solo_Family <- as.factor(all$Solo_Family)
#################################
##############Cabin##############
all$Cabin <- substr(all$Cabin,1,1)
all$Cabin[all$Cabin == ''] <- 'Unknown'
all$Cabin <- factor(all$Cabin)

######################################
all$sex_age <- factor(paste(all$Sex,all$cat_age))
all$Sex <- factor(all$Sex)
all$Pclass <- factor(all$Pclass,ordered = T)
all$Embarked <- factor(all$Embarked)
all$group <- factor(all$group)
all <- all %>% select(-c(PassengerId,Ticket,Name))
glimpse(all)

```
EDA Training set & add feature
```{r}
trainingset <- all %>% filter(Train_or_Test=="Train") %>%
  select(-Train_or_Test)
glimpse(trainingset)

ggplot(data=trainingset,aes(x=Survived,fill=Survived))+
  geom_bar()+
  theme_classic()

ggplot(data=trainingset,aes(x=Pclass,fill=Survived))+
  geom_bar(position=position_dodge())

ggplot(data=trainingset,aes(x=Sex,fill=Survived))+
  geom_bar(position=position_dodge())

ggplot(data=trainingset,aes(x=Embarked,fill=Survived))+
  geom_bar(position = position_dodge())

ggplot(data=trainingset,aes(x=SibSp,fill=Survived))+
  geom_bar(position = position_dodge())

ggplot(data=trainingset,aes(x=Parch,fill=Survived))+
  geom_bar(position = position_dodge())

ggplot(data=trainingset,aes(x=Num_Family,fill=Survived))+
  geom_bar(position = position_dodge())

ggplot(data = trainingset,aes(x=sex_age,fill = Survived))+
  geom_bar(position = position_dodge())

for (i in 1:nrow(all)) {
  if(all[i,'Num_Family'] == 1) {
    all$alone[i]=1
  } else {
    all$alone[i]=0
  }
}
all$alone <- factor(all$alone)
#### Embarked missing value######
trainingset[trainingset$Embarked == "",]
train[c(62,830),]  
ggplot(data = trainingset[-c(62,830),], aes(x = Embarked,y = Fare , fill = Pclass))+
  geom_boxplot(position = position_dodge())
ggplot(data = trainingset[-c(62,830),],aes(x = Pclass, y = Fare ,fill = Embarked))+
  geom_boxplot(position = position_dodge())

summary(train$Fare[train$Embarked =="S" & train$Pclass == 1])  # Median 52.00
summary(train$Fare[train$Embarked =="C" & train$Pclass == 1])  # Median 78.27
all[c(62,830),"Embarked"] <- "C"
all$Embarked <- factor(all$Embarked)
levels(all$Embarked)

all$social_grade <- paste(all$Pclass,all$sex_age)
all$social_grade <- factor(all$social_grade)
levels(all$social_grade)

all$baby <- "Not Baby" 
all$baby[all$Age < 10] <- "Baby"
all$baby <- factor(all$baby)
```
Modeling
```{r}

### Modeling ######
all_rf <- all  #copy
all$Survived <- as.numeric(all$Survived)
all$Survived <- all$Survived - 1
##
train <- all %>% filter(Train_or_Test == "Train") %>% select(c(Survived,Pclass,Sex,Age,Parent,social_grade,alone,
                                                               Fare,Embarked,group,Solo_Family,baby,
                                                               sex_age,Train_or_Test,Cabin)) %>% select(-Train_or_Test)
test <- all %>% filter(Train_or_Test == "Test") %>% select(c(Survived,Pclass,Sex,Age,Parent,social_grade,alone,
                                                             Fare,Embarked,group,Solo_Family,baby,
                                                             sex_age,Train_or_Test,Cabin)) %>% select(-Train_or_Test)

train_label <- train$Survived
test_label <- test$Survived   
### 

x_train <- model.matrix(~.-1, data = train[,-1]) %>% data.frame
x_test <- model.matrix(~.-1, data = test[,-1]) %>% data.frame

dtrain <- xgb.DMatrix(data = as.matrix(x_train),
                      label = train_label)
dtest <- xgb.DMatrix(data = as.matrix(x_test))

set.seed(930217)
xgb_cv <- xgboost::xgb.cv(
  data = dtrain,
  objective = "binary:logistic", verbos = 1,
  nrounds = 1000, subsample = 0.67,
  colsample_bytree = 0.8,
  nfold = 5, eta = 0.01, gamma = 0,
  early_stopping_rounds = 100, max_depth = 4,
  min_child_weight = 5, alpha = 0.5
)
str(all)
bst <- xgb_cv$best_iteration

params <- list(
  objective = "reg:logistic",
  eval_metric = "auc",
  eta = 0.01,
  gamma = 0,
  max_depth = 4,
  sub_sample =0.67, 
  colsample_bytree = 0.8,
  nthread = -1,
  min_child_weight = 5,
  alpha = 0.5
)

set.seed(0514) 
fitting_xgb <- xgb.train(data = dtrain, params = params,nrounds = bst)

prediction_xgb <- predict(fitting_xgb,dtest)

prediction_xgb

###### importance #########
xgb.importance(colnames(dtrain), model = fitting_xgb) %>%
  xgb.plot.importance(top_n = 10)

######### RandomForest ###########
train_rf <- all_rf %>% filter(Train_or_Test == "Train") %>% select(c(Survived,Pclass,Sex,Age,Parent,social_grade,alone,
                                                               Fare,Embarked,group,Solo_Family,baby,
                                                               sex_age,Train_or_Test,Cabin)) %>% select(-Train_or_Test)
test_rf <- all_rf %>% filter(Train_or_Test == "Test") %>% select(c(Survived,Pclass,Sex,Age,Parent,social_grade,alone,
                                                             Fare,Embarked,group,Solo_Family,baby,
                                                             sex_age,Train_or_Test,Cabin)) %>% select(-Train_or_Test)

train_label <- train_rf$Survived
test_label <- test_rf$Survived  

x_train_rf <- model.matrix(~.-1, data = train_rf[,-1]) %>% data.frame
x_test_rf <- model.matrix(~.-1, data = test_rf[,-1]) %>% data.frame

my_control <- trainControl(method="cv", number = 5, verboseIter = F, returnData = F)

set.seed(42)
fitting_rf <- ranger(train_label~.,x_train_rf,mtry = 6,
                     probability = T)
fitting_rf

prediction_rf <- predict(fitting_rf,x_test_rf)
prediction_rf <- prediction_rf$predictions
prediction_rf <- prediction_rf[,2]
prediction_rf


#### LightGBM ####
x_train <- model.matrix(~.-1, data = train_rf[,-1])
x_test <- model.matrix(~.-1,data = test_rf[,-1])

train.lgb <- lgb.Dataset(data = x_train, label = train[,1])



set.seed(9)
lgb.grid <- list(objective = "binary",
                metric = "auc",
                learing_rate = 0.01,
                num_leaves = 15,
                feature_fraction = 0.7,
                bagging_fraction = 0.7,
                bagging_freq = 5
                )
lgb.cv <- lgb.cv(param=lgb.grid, data=train.lgb, learning_rate = 0.01, num_leaves = 15, num_threads = 4, 
                nrounds = 5000, early_stopping_rounds = 50, eval_freq = 20, nfold = 5, stratified = F)               

best_iter <- lgb.cv$best_iter
set.seed(9)
fitting_lgb <- lgb.train(params = lgb.grid,data = train.lgb,learning_rate = 0.01,nrounds = best_iter, eval_freq = 100)


prediction_lgb <- predict(fitting_lgb,x_test)
prediction_lgb

```
Create Output
```{r}
Passengerid <- 892:1309
df_ <- data.frame(Passengerid,prediction_xgb,prediction_rf,prediction_lgb)
df_$prediction <- prediction_xgb + prediction_rf + prediction_lgb 
df_$rank <- rank(df_$prediction)

####### Create Normalization Function #######
normalized <- function(x) {
    (x - min(x)) / (max(x) - min(x))
}
###########################################
df_$normailzed_rank <- normalized(df_$rank)

df_ensemble_rank <- data.frame(Passengerid,df_$normailzed_rank)

write.csv(df_ensemble_rank,"ensemble_submission.csv",row.names = F)
```


